name: Code Scanning

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions: write-all

jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-22.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.2.0

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitLeaks Scanning
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trufflehog Scanning
        uses: trufflesecurity/trufflehog@v3.91.1
        with:
          extra_args: --results=verified,unknown

  codeql-scanning:
    name: CodeQL Scanning
    runs-on: ubuntu-latest
    # container: catthehacker/ubuntu:act-22.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      # - name: Setup MTK Certification
      #   uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.2.0

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: CodeQL Initialize
        uses: github/codeql-action/init@v4.31.5

      - name: CodeQL Analyze
        uses: github/codeql-action/analyze@v4.31.5
